### ISSUE TITLE
Cache wasn't restored successfully

### ISSUE THREAD

**Issue by kenorb** [johelegp/gcc-snapshot#2]
I don't think caching works properly.

First run worked fine:

```
Run johelegp/gcc-snapshot@v1
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/Foo/Bar --files-from manifest.txt
Cache Size: ~0 MB (22 B)
Cache saved successfully
...
Run g++ --version
g++ (GCC) 13.0.0 20220911 (experimental)
```

Second run, restored cache, but g++ is the same as it was before:

```
Run johelegp/gcc-snapshot@v1
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/eb5035af-977b-.../cache.tzst -P -C /home/runner/work/Foo/Bar
Cache restored successfully
...
Run g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by JohelEGP** [comment]
Thank you for reporting this.

It seems that caching always succeeds with 22 bytes. Perhaps something changed with the condition of restorage, since this used to work.
https://github.com/JohelEGP/gcc-snapshot/blob/c7b5c01d2429d0708bdd1bd80da5b1ece8f792fb/index.js#L16
https://github.com/JohelEGP/gcc-snapshot/blob/c7b5c01d2429d0708bdd1bd80da5b1ece8f792fb/index.js#L41-L42

I actually wanted this to be a composite action rather than a JavaScript action. Now that the limitations of composite actions have been lifted, perhaps I can restore the original composite action.

**Comment by masx200** [comment]
```yml
 - uses: actions/cache@v3
        id: cache-gcc-13
        with:
          path: |
            /opt/gcc-latest/

          key: ${{ runner.os }}-gcc-13
```

```yml

      - name: install-gcc-13
        if: steps.cache-gcc-13.outputs.cache-hit != 'true'
        run: |
          wget http://kayari.org/gcc-latest/gcc-latest.deb && sudo dpkg -i gcc-latest.deb && rm gcc-latest.deb
```
